### ISSUE TITLE
why i can't render my  html on    .ecr file ?

### ISSUE THREAD

**Issue by extremety1989** [samueleaton/raze#12] opened 2017-11-15 13:39 UTC
Here is my code
it just shows html, but does not render it ...

require "raze"
Raze.config.static_dir = "./public"
get "/" do
  render "src/views/index.ecr"
end

Raze.run

**Comment by samueleaton** [comment] 2017-11-16 01:23
I just tried it and it works fine for me. When you say that it shows the HTML, do you mean it shows the tags as plain text?

**Comment by extremety1989** [comment] 2017-11-20 18:02
yes,it just shows plain text !

**Comment by extremety1989** [comment] 2017-11-20 19:39
@samueleaton yes,it just shows plain text !

**Comment by extremety1989** [comment] 2017-11-21 09:38
@samueleaton here is my code

require "raze"

get "/" do
      render "views/layout.ecr"
end

get "/api/users" do |ctx|
  ctx.response.content_type = "application/json"
  [{"user_id" => "abc"}, {"user_id" => "xyz"}].to_json
end


Raze.run

**Comment by z64** [comment] 2017-11-21 14:55
Could you share the ECR file, so that we have the full example that we could run?

**Comment by extremety1989** [comment] 2017-11-21 16:51
@z64 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/navbar.css">
<link rel="stylesheet" href="/css/footer.css">
<div id="nav"></div>
<section>
<div id="main"></div>
</section>
<div id="footer"></div>
<script src="/js/pages.js"></script>
<script src="/js/app.js"></script>

**Comment by extremety1989** [comment] 2017-11-21 16:51
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/navbar.css">
<link rel="stylesheet" href="/css/footer.css">
<div id="nav"></div>
<section>
<div id="main"></div>
</section>
<div id="footer"></div>
<script src="/js/pages.js"></script>
<script src="/js/app.js"></script>

**Comment by extremety1989** [comment] 2017-11-21 16:53
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/navbar.css">
<link rel="stylesheet" href="/css/footer.css">
<div id="nav"></div>
<section>
<div id="main"></div>
</section>
<div id="footer"></div>
<script src="/js/pages.js"></script>
<script src="/js/app.js"></script>``

**Comment by extremety1989** [comment] 2017-11-21 16:53
as you can see there is othing special, rendering in Kemal works

**Comment by z64** [comment] 2017-11-21 17:06
I can't reproduce this on Chrome 62
```
$ shards list
Shards installed:
  * raze (0.1.0)
  * radix (0.3.8)
  * kilt (0.4.0)
$ cr -v
Crystal 0.23.1 (2017-09-10) LLVM 5.0.0
```
`test.cr`
```cr
require "raze"

get "/" do
  render "views/layout.ecr"
end

get "/api/users" do |ctx|
  ctx.response.content_type = "application/json"
  [{"user_id" => "abc"}, {"user_id" => "xyz"}].to_json
end

Raze.config.port = 8080
Raze.run
```
`views/layout.ecr`
```html
<script src="/js/pages.js"></script> <script src="/js/app.js"></script>
```
I get a blank page at http://zsixtyfour.com:8080/

**Comment by extremety1989** [comment] 2017-11-21 17:20
@z64  well as i try to paste whole html here, it just pastes only this 
<script src="/js/pages.js"></script> <script src="/js/app.js"></script>

**Comment by z64** [comment] 2017-11-21 17:21
Sorry, I don't follow. You can't paste the HTML into *github?*

If so, use https://hastebin.com/ or similar. Or https://gist.github.com/

**Comment by extremety1989** [comment] 2017-11-21 17:23
Save New Duplicate & Edit Just Text Twitter
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/navbar.css">
<link rel="stylesheet" href="/css/footer.css">
<link rel="stylesheet" href="/css/login.css">
<link rel="stylesheet" href="/css/register.css">
<link rel="stylesheet" href="/css/home.css">
<link rel="stylesheet" href="/css/forgot.css">
<link rel="stylesheet" href="/css/notes.css">
<div id="display">
<div id="nav"></div>
<div id="main"></div>
<div id="footer"></div>
</div>
<script src="/js/pages.js"></script>
<script src="/js/app.js"></script>

**Comment by z64** [comment] 2017-11-21 17:24
You need to press the Save icon on the right and share the URL from your browser here..

**Comment by extremety1989** [comment] 2017-11-21 17:25
@z64 
https://hastebin.com/afazuhuduc.xml

**Comment by z64** [comment] 2017-11-21 17:28
You need to wrap your html in `<html></html>` tags.

**Comment by extremety1989** [comment] 2017-11-21 17:29
@z64 okey let me try that, because in Kemal i dont use wrap of html

**Comment by z64** [comment] 2017-11-21 17:29
Kemal (or maybe its templating engine, i'm unfamiliar) may do this automatically. But this works for me: http://zsixtyfour.com:8080/

**Comment by extremety1989** [comment] 2017-11-21 17:31
@z64  aaa yes it works now !

👍  thank you !

**Comment by z64** [comment] 2017-11-21 17:31
No problem :+1: 

If you're all set, please close the issue. Have fun!

**Closed as completed** 2017-11-21 17:32 UTC
